server:
    origin: http://example.com

db:
    host: 'localhost'
    username: 'your-postgres-username'
    password: 'your-postgres-password'
    migrationsRun: false
    synchronize: false

jwt:
    secret: 'secret-key'

redis:
    host: 'localhost'
    port: 6379
    ttl: 20
    max: 100
